/**
# COPYRIGHT LICENSE: 
# This information contains sample code provided in source code form. You may 
# copy, modify, and distribute these sample programs in any form without 
# payment to IBM for the purposes of developing, using, marketing or 
# distributing application programs conforming to the application programming
# interface for the operating platform for which the sample code is written. 
# Notwithstanding anything to the contrary, IBM PROVIDES THE SAMPLE SOURCE CODE
# ON AN "AS IS" BASIS AND IBM DISCLAIMS ALL WARRANTIES, EXPRESS OR IMPLIED, 
# INCLUDING, BUT NOT LIMITED TO, ANY IMPLIED WARRANTIES OR CONDITIONS OF 
# MERCHANTABILITY, SATISFACTORY QUALITY, FITNESS FOR A PARTICULAR PURPOSE, 
# TITLE, AND ANY WARRANTY OR CONDITION OF NON-INFRINGEMENT. IBM SHALL NOT BE 
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL OR CONSEQUENTIAL DAMAGES
# ARISING OUT OF THE USE OR OPERATION OF THE SAMPLE SOURCE CODE. IBM HAS NO 
# OBLIGATION TO PROVIDE MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS OR 
# MODIFICATIONS TO THE SAMPLE SOURCE CODE.
 **/
package org.apache.axis2.jaxws.sample.mtom;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0_01-b15-fcs
 * Generated source version: 2.0
 * 
 */
@WebService(name = "MtomSampleService", 
	    targetNamespace = "http://org/apache/axis2/jaxws/sample/mtom/",
	    wsdlLocation = "WEB-INF/wsdl/ImageDepot.wsdl")
public interface MtomSample {


    /**
     * 
     * @param input
     * @return
     *     returns org.apache.axis2.jaxws.sample.mtom.ImageDepot
     */
    @WebMethod(action="sendImage")
    @WebResult(name = "output", targetNamespace = "http://org/apache/axis2/jaxws/sample/mtom/")
    @RequestWrapper(localName = "sendImage", targetNamespace = "http://org/apache/axis2/jaxws/sample/mtom/", className = "org.apache.axis2.jaxws.sample.mtom.SendImage")
    @ResponseWrapper(localName = "sendImageResponse", targetNamespace = "http://org/apache/axis2/jaxws/sample/mtom/", className = "org.apache.axis2.jaxws.sample.mtom.SendImageResponse")
    public ImageDepot sendImage(
        @WebParam(name = "input", targetNamespace = "http://org/apache/axis2/jaxws/sample/mtom/")
        ImageDepot input);

   
}
