
package com.ibm.was.wssample.sei.ping;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0_01-b15-fcs
 * Generated source version: 2.0
 * 
 */
@WebService(name = "PingServicePortType", targetNamespace = "http://com/ibm/was/wssample/sei/ping/")
@SOAPBinding(parameterStyle = ParameterStyle.BARE)
public interface PingServicePortType {


    /**
     * 
     * @param parameter
     */
    @WebMethod(action = "pingOperation")
    @Oneway
    public void pingOperation(
        @WebParam(name = "pingStringInput", targetNamespace = "http://com/ibm/was/wssample/sei/ping/", partName = "parameter")
        PingStringInput parameter);

}
