<?xml version="1.0" encoding="UTF-8"?>
<!--
# COPYRIGHT LICENSE: 
# This information contains sample code provided in source code form. You may 
# copy, modify, and distribute these sample programs in any form without 
# payment to IBM for the purposes of developing, using, marketing or 
# distributing application programs conforming to the application programming
# interface for the operating platform for which the sample code is written. 
# Notwithstanding anything to the contrary, IBM PROVIDES THE SAMPLE SOURCE CODE
# ON AN "AS IS" BASIS AND IBM DISCLAIMS ALL WARRANTIES, EXPRESS OR IMPLIED, 
# INCLUDING, BUT NOT LIMITED TO, ANY IMPLIED WARRANTIES OR CONDITIONS OF 
# MERCHANTABILITY, SATISFACTORY QUALITY, FITNESS FOR A PARTICULAR PURPOSE, 
# TITLE, AND ANY WARRANTY OR CONDITION OF NON-INFRINGEMENT. IBM SHALL NOT BE 
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL OR CONSEQUENTIAL DAMAGES
# ARISING OUT OF THE USE OR OPERATION OF THE SAMPLE SOURCE CODE. IBM HAS NO 
# OBLIGATION TO PROVIDE MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS OR 
# MODIFICATIONS TO THE SAMPLE SOURCE CODE.
 -->
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:tns="http://com/ibm/was/wssample/sei/ping/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="PingService"
	targetNamespace="http://com/ibm/was/wssample/sei/ping/">
	<wsdl:types>
		<xsd:schema
			targetNamespace="http://com/ibm/was/wssample/sei/ping/"
			xmlns:xsd="http://www.w3.org/2001/XMLSchema">


			<xsd:element name="pingStringInput">
				<xsd:complexType>
					<xsd:sequence>
						<xsd:element name="pingInput" type="xsd:string" />
					</xsd:sequence>
				</xsd:complexType>
			</xsd:element>
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="pingOperationRequest">
		<wsdl:part element="tns:pingStringInput" name="parameter" />
	</wsdl:message>
	<wsdl:portType name="PingServicePortType">
		<wsdl:operation name="pingOperation">
			<wsdl:input message="tns:pingOperationRequest" />

		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="PingSOAP" type="tns:PingServicePortType">
		<soap:binding style="document"
			transport="http://schemas.xmlsoap.org/soap/http" />
		<wsdl:operation name="pingOperation">
			<soap:operation soapAction="pingOperation" style="document" />
			<wsdl:input>
				<soap:body use="literal" />
			</wsdl:input>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="PingService">
		<wsdl:port binding="tns:PingSOAP" name="PingServicePort">
			<soap:address
				location="http://localhost:9080/WSSampleSei/PingService" />
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
